let styleList2 = [
  { key: 'width', val: 'width' },
  { key: 'height', val: 'height' },
  { key: 'opacity', val: 'opacity' },
  { key: 'visibility', val: 'visibility' },
  { key: 'background-position', val: 'bgp' },
  { key: 'padding', val: 'padding' },
  { key: 'border-width', val: 'borderWidth' },
  { key: 'border-color', val: 'borderColor' },
  { key: 'position', val: 'position' },
  { key: 'left', val: 'left' },
  { key: 'top', val: 'top' },
  { key: 'transform', val: 'transform' },
  { key: 'transform-origin', val: 'transformOrigin' },
]

let styleList1 = [
  { key: 'flex', val: 'flex' },
  { key: 'right', val: 'right' },
  { key: 'bottom', val: 'bottom' },
  { key: 'padding-left', val: 'paddingLeft' },
  { key: 'padding-right', val: 'paddingRight' },
  { key: 'padding-top', val: 'paddingTop' },
  { key: 'padding-bottom', val: 'paddingBottom' },
  { key: 'margin-left', val: 'marginLeft' },
  { key: 'margin-right', val: 'marginRight' },
  { key: 'margin-top', val: 'marginTop' },
  { key: 'margin-bottom', val: 'marginBottom' },
  { key: 'border-left-width', val: 'bdLeftWidth' },
  { key: 'border-right-width', val: 'bdRightWidth' },
  { key: 'border-top-width', val: 'bdTopWidth' },
  { key: 'border-bottom-width', val: 'bdBottomWidth' },
  { key: 'border-left-color', val: 'bdLeftColor' },
  { key: 'border-right-color', val: 'bdRightColor' },
  { key: 'background-color', val: 'bgc' },
  { key: 'border-top-color', val: 'bdTopColor' },
  { key: 'border-bottom-color', val: 'bdBottomColor' },
]

export { styleList2, styleList1 }
